language: go
os: osx
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-odo
  - brew tap --repair
script:
  - brew audit odo
  - brew install -v odo
  - brew test odo